/* ============================================================
   OAO Course Overviews — manifest
   ------------------------------------------------------------
   To add a course:
     1. Drop its PDF into the pdfs/ folder
        (lowercase-with-hyphens.pdf, e.g. grade-4-science.pdf)
     2. Add one entry below:
        { title: "Course Name", grades: ["4"], file: "pdfs/grade-4-science.pdf" }
   Grade values: "K", "1" ... "12".
   A course may list several grades (e.g. an elective for 6–8:
   grades: ["6","7","8"]) and it will appear under each one,
   tagged "Grades 6–8" on its row. The tag is auto-generated as
   first–last; add band: "..." to override it (e.g. a course for
   every grade: grades: ["K","1",...,"12"], band: "All grades").
   Then commit + push. The widget updates itself from this list.
   ============================================================ */
window.COURSE_MANIFEST = {
  updated: "2026-06-08",
  courses: [
    { title: "Kindergarten Language Arts", grades: ["K"], file: "pdfs/grade-k-language-arts.pdf" },
    { title: "Kindergarten Mathematics", grades: ["K"], file: "pdfs/grade-k-math.pdf" },
    { title: "Kindergarten Science", grades: ["K"], file: "pdfs/grade-k-science.pdf" },
    { title: "Kindergarten Social Studies", grades: ["K"], file: "pdfs/grade-k-social-studies.pdf" },
    { title: "Kindergarten Art", grades: ["K"], file: "pdfs/art-k.pdf" },
    { title: "Kindergarten Music", grades: ["K"], file: "pdfs/music-k.pdf" },
    { title: "Kindergarten Physical Education", grades: ["K"], file: "pdfs/grade-k-pe.pdf" },
    { title: "1st Grade Language Arts", grades: ["1"], file: "pdfs/grade-1-language-arts.pdf" },
    { title: "1st Grade Mathematics", grades: ["1"], file: "pdfs/grade-1-math.pdf" },
    { title: "1st Grade Science", grades: ["1"], file: "pdfs/grade-1-science.pdf" },
    { title: "1st Grade Social Studies", grades: ["1"], file: "pdfs/grade-1-social-studies.pdf" },
    { title: "1st Grade Art", grades: ["1"], file: "pdfs/art-grade-1.pdf" },
    { title: "1st Grade Music", grades: ["1"], file: "pdfs/music-grade-1.pdf" },
    { title: "1st Grade Physical Education", grades: ["1"], file: "pdfs/grade-1-pe.pdf" },
    { title: "2nd Grade Language Arts", grades: ["2"], file: "pdfs/grade-2-language-arts.pdf" },
    { title: "2nd Grade Mathematics", grades: ["2"], file: "pdfs/grade-2-math.pdf" },
    { title: "2nd Grade Science", grades: ["2"], file: "pdfs/grade-2-science.pdf" },
    { title: "2nd Grade Social Studies", grades: ["2"], file: "pdfs/grade-2-social-studies.pdf" },
    { title: "2nd Grade Art", grades: ["2"], file: "pdfs/art-grade-2.pdf" },
    { title: "2nd Grade Music", grades: ["2"], file: "pdfs/music-grade-2.pdf" },
    { title: "2nd Grade Physical Education", grades: ["2"], file: "pdfs/grade-2-pe.pdf" },
    { title: "3rd Grade Language Arts", grades: ["3"], file: "pdfs/grade-3-language-arts.pdf" },
    { title: "3rd Grade Mathematics", grades: ["3"], file: "pdfs/grade-3-math.pdf" },
    { title: "3rd Grade Science", grades: ["3"], file: "pdfs/grade-3-science.pdf" },
    { title: "3rd Grade Social Studies", grades: ["3"], file: "pdfs/grade-3-social-studies.pdf" },
    { title: "3rd Grade Art", grades: ["3"], file: "pdfs/art-intermediate-1.pdf" },
    { title: "3rd Grade Music", grades: ["3"], file: "pdfs/music-intermediate-1.pdf" },
    { title: "3rd Grade Physical Education", grades: ["3"], file: "pdfs/grade-3-pe.pdf" },
    { title: "4th Grade Language Arts", grades: ["4"], file: "pdfs/grade-4-language-arts.pdf" },
    { title: "4th Grade Mathematics", grades: ["4"], file: "pdfs/grade-4-math.pdf" },
    { title: "4th Grade Science", grades: ["4"], file: "pdfs/grade-4-science.pdf" },
    { title: "4th Grade Social Studies", grades: ["4"], file: "pdfs/grade-4-social-studies.pdf" },
    { title: "4th Grade Art", grades: ["4"], file: "pdfs/art-intermediate-2.pdf" },
    { title: "4th Grade Music", grades: ["4"], file: "pdfs/music-intermediate-2.pdf" },
    { title: "4th Grade Physical Education", grades: ["4"], file: "pdfs/grade-4-pe.pdf" },
    { title: "5th Grade Language Arts", grades: ["5"], file: "pdfs/grade-5-language-arts.pdf" },
    { title: "5th Grade Mathematics", grades: ["5"], file: "pdfs/grade-5-math.pdf" },
    { title: "5th Grade Science", grades: ["5"], file: "pdfs/grade-5-science.pdf" },
    { title: "5th Grade Social Studies", grades: ["5"], file: "pdfs/grade-5-social-studies.pdf" },
    { title: "5th Grade Art", grades: ["5"], file: "pdfs/art-intermediate-3.pdf" },
    { title: "5th Grade Music", grades: ["5"], file: "pdfs/music-intermediate-3.pdf" },
    { title: "5th Grade Physical Education", grades: ["5"], file: "pdfs/grade-5-pe.pdf" },
    { title: "Elementary Latin", grades: ["3", "4", "5"], file: "pdfs/elementary-latin.pdf" },
    { title: "6th Grade English Language Arts", grades: ["6"], file: "pdfs/grade-6-ela.pdf" },
    { title: "6th Grade Mathematics", grades: ["6"], file: "pdfs/grade-6-math.pdf" },
    { title: "M/J Comprehensive Science 1", grades: ["6"], file: "pdfs/mj-comprehensive-science-1.pdf" },
    { title: "6th Grade Digital Discoveries", grades: ["6"], file: "pdfs/grade-6-digital-discoveries.pdf" },
    { title: "6th Grade Physical Education (M/J Fitness)", grades: ["6"], file: "pdfs/mj-fitness-grade-6.pdf" },
    { title: "7th Grade English Language Arts", grades: ["7"], file: "pdfs/grade-7-ela.pdf" },
    { title: "7th Grade Mathematics", grades: ["7"], file: "pdfs/grade-7-math.pdf" },
    { title: "M/J Comprehensive Science 2", grades: ["7"], file: "pdfs/mj-comprehensive-science-2.pdf" },
    { title: "U.S. History (1492-Reconstruction)", grades: ["7"], file: "pdfs/grade-7-us-history.pdf" },
    { title: "7th Grade Digital Discoveries", grades: ["7"], file: "pdfs/grade-7-digital-discoveries.pdf" },
    { title: "7th Grade Physical Education", grades: ["7"], file: "pdfs/grade-7-pe.pdf" },
    { title: "8th Grade English Language Arts", grades: ["8"], file: "pdfs/grade-8-ela.pdf" },
    { title: "8th Grade Pre-Algebra", grades: ["8"], file: "pdfs/grade-8-pre-algebra.pdf" },
    { title: "M/J Comprehensive Science 3", grades: ["8"], file: "pdfs/mj-comprehensive-science-3.pdf" },
    { title: "Civics", grades: ["8"], file: "pdfs/grade-8-civics.pdf" },
    { title: "8th Grade Digital Discoveries", grades: ["8"], file: "pdfs/grade-8-digital-discoveries.pdf" },
    { title: "8th Grade Physical Education", grades: ["8"], file: "pdfs/grade-8-pe.pdf" },
    { title: "Critical Thinking Skills", grades: ["6", "7", "8"], file: "pdfs/critical-thinking.pdf" },
    { title: "M/J Music Theory 1", grades: ["6", "7", "8"], file: "pdfs/mj-music-theory-1.pdf" },
    { title: "M/J Music Theory 2", grades: ["6", "7", "8"], file: "pdfs/mj-music-theory-2.pdf" },
    { title: "M/J Visual Art 1", grades: ["6", "7", "8"], file: "pdfs/mj-visual-art-1.pdf" },
    { title: "M/J Visual Art 2", grades: ["6", "7", "8"], file: "pdfs/mj-visual-art-2.pdf" },
    { title: "M/J Visual Art 3", grades: ["6", "7", "8"], file: "pdfs/mj-visual-art-3.pdf" },
    { title: "M/J Latin, Beginning", grades: ["6", "7", "8"], file: "pdfs/mj-latin-beginning.pdf" },
    { title: "M/J Latin, Intermediate", grades: ["6", "7", "8"], file: "pdfs/mj-latin-intermediate.pdf" },
    { title: "M/J Latin, Advanced", grades: ["6", "7", "8"], file: "pdfs/mj-latin-advanced.pdf" },
    { title: "M/J Spanish, Beginning", grades: ["6", "7", "8"], file: "pdfs/mj-spanish-beginning.pdf" },
    { title: "M/J Spanish, Intermediate", grades: ["6", "7", "8"], file: "pdfs/mj-spanish-intermediate.pdf" },
    { title: "9th Grade English (English 1)", grades: ["9"], file: "pdfs/grade-9-ela.pdf" },
    { title: "World History", grades: ["9"], file: "pdfs/grade-9-world-history.pdf" },
    { title: "Algebra 1", grades: ["9"], file: "pdfs/algebra-1.pdf" },
    { title: "Algebra 1 Honors", grades: ["9"], file: "pdfs/algebra-1-honors.pdf" },
    { title: "Biology 1", grades: ["9"], file: "pdfs/biology-1.pdf" },
    { title: "Integrated Science 1", grades: ["9"], file: "pdfs/integrated-science-1.pdf" },
    { title: "10th Grade English (English 2)", grades: ["10"], file: "pdfs/grade-10-ela.pdf" },
    { title: "English 2 Honors", grades: ["10"], file: "pdfs/english-2-honors.pdf" },
    { title: "U.S. History", grades: ["10"], file: "pdfs/grade-10-us-history.pdf" },
    { title: "11th Grade English (English 3)", grades: ["11"], file: "pdfs/grade-11-ela.pdf" },
    { title: "English 3 Honors", grades: ["11"], file: "pdfs/english-3-honors.pdf" },
    { title: "AP English Language & Composition", grades: ["11"], file: "pdfs/ap-english-language.pdf" },
    { title: "U.S. Government Honors", grades: ["11"], file: "pdfs/grade-11-us-government-honors.pdf" },
    { title: "Economics Honors", grades: ["11"], file: "pdfs/economics-honors.pdf" },
    { title: "12th Grade English (English 4)", grades: ["12"], file: "pdfs/grade-12-ela.pdf" },
    { title: "Algebra 2", grades: ["10", "11"], file: "pdfs/algebra-2.pdf" },
    { title: "Geometry", grades: ["9", "10"], file: "pdfs/geometry.pdf" },
    { title: "Geometry Honors", grades: ["9", "10"], file: "pdfs/geometry-honors.pdf" },
    { title: "Precalculus Honors", grades: ["11", "12"], file: "pdfs/precalculus-honors.pdf" },
    { title: "Calculus Honors", grades: ["12"], file: "pdfs/calculus-honors.pdf" },
    { title: "Probability & Statistics Honors", grades: ["11", "12"], file: "pdfs/probability-statistics-honors.pdf" },
    { title: "Chemistry 1 Honors", grades: ["10", "11"], file: "pdfs/chemistry-1-honors.pdf" },
    { title: "Physics 1", grades: ["11", "12"], file: "pdfs/physics-1.pdf" },
    { title: "Physics 1 Honors", grades: ["11", "12"], file: "pdfs/physics-1-honors.pdf" },
    { title: "Anatomy & Physiology", grades: ["11", "12"], file: "pdfs/anatomy-physiology.pdf" },
    { title: "Spanish 1", grades: ["9", "10", "11", "12"], file: "pdfs/spanish-1.pdf" },
    { title: "Spanish 2", grades: ["9", "10", "11", "12"], file: "pdfs/spanish-2.pdf" },
    { title: "Spanish 3 Honors", grades: ["9", "10", "11", "12"], file: "pdfs/spanish-3-honors.pdf" },
    { title: "Spanish 4 Honors", grades: ["9", "10", "11", "12"], file: "pdfs/spanish-4-honors.pdf" },
    { title: "French 1", grades: ["9", "10", "11", "12"], file: "pdfs/french-1.pdf" },
    { title: "Latin 1", grades: ["9", "10", "11", "12"], file: "pdfs/latin-1.pdf" },
    { title: "Latin 2", grades: ["9", "10", "11", "12"], file: "pdfs/latin-2.pdf" },
    { title: "Latin 3 Honors", grades: ["9", "10", "11", "12"], file: "pdfs/latin-3-honors.pdf" },
    { title: "2-D Studio Art 1", grades: ["9", "10", "11", "12"], file: "pdfs/2d-studio-art-1.pdf" },
    { title: "2-D Studio Art 2", grades: ["9", "10", "11", "12"], file: "pdfs/2d-studio-art-2.pdf" },
    { title: "2-D Studio Art 3 Honors", grades: ["9", "10", "11", "12"], file: "pdfs/2d-studio-art-3-honors.pdf" },
    { title: "Digital Art & Imaging 1", grades: ["9", "10", "11", "12"], file: "pdfs/digital-art-imaging-1.pdf" },
    { title: "Creative Photography 1", grades: ["9", "10", "11", "12"], file: "pdfs/creative-photography-1.pdf" },
    { title: "Art History & Criticism 1 Honors", grades: ["9", "10", "11", "12"], file: "pdfs/art-history-criticism-1-honors.pdf" },
    { title: "Introduction to Art History", grades: ["9", "10", "11", "12"], file: "pdfs/intro-to-art-history.pdf" },
    { title: "Music of the World", grades: ["9", "10", "11", "12"], file: "pdfs/music-of-the-world.pdf" },
    { title: "Humanities Survey", grades: ["9", "10", "11", "12"], file: "pdfs/humanities-survey.pdf" },
    { title: "Sociology", grades: ["9", "10", "11", "12"], file: "pdfs/sociology.pdf" },
    { title: "Philosophy Honors", grades: ["11", "12"], file: "pdfs/philosophy-honors.pdf" },
    { title: "Semantics & Logic Honors", grades: ["9", "10", "11", "12"], file: "pdfs/semantics-logic-honors.pdf" },
    { title: "Journalism 1", grades: ["9", "10", "11", "12"], file: "pdfs/journalism-1.pdf" },
    { title: "Discovering Computer Science", grades: ["9", "10", "11", "12"], file: "pdfs/discovering-computer-science.pdf" },
    { title: "Financial Literacy", grades: ["9", "10", "11", "12"], file: "pdfs/financial-literacy.pdf" },
    { title: "Driver Education", grades: ["9", "10", "11", "12"], file: "pdfs/drivers-ed.pdf" },
    { title: "HOPE — Health Opportunities through PE", grades: ["9", "10", "11", "12"], file: "pdfs/hope.pdf" },
    { title: "Career Research & Decision Making", grades: ["9", "10", "11", "12"], file: "pdfs/career-research-decision-making.pdf" },
    { title: "Critical Thinking, Study Skills & Destination College", grades: ["9", "10", "11", "12"], file: "pdfs/critical-thinking-study-skills.pdf" }
  ]
};
